_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
langcode: fi
ignored_config_entities:
  - 'webform.webform.*'
  - 'devel.*'
  - system.site
  - uhsg_service_provider_details.settings
  - 'xmlsitemap_engines.*'
  - 'google_tag.*'
