add_page_meta: true
output_terms: true
output_fields: false
group: false
lib_helper: false
entity_meta:
  created: created
  langcode: langcode
  status: status
  uid: uid
  uuid: uuid
  vid: vid
  name: '0'
enable_ia: false
ia_depth: 3
ia_category_primary: primaryCategory
ia_category_sub: subCategory
vocabs:
  accessibility: '0'
  building: '0'
  campus: '0'
  contacts: '0'
  equipment: '0'
  price_categories: '0'
  room_type: '0'
expose_user_details: '*'
expose_user_details_roles:
  authenticated: '0'
  admin: '0'
  editor: '0'
current_user_meta:
  name: '0'
  mail: '0'
  roles: '0'
  created: '0'
  access: '0'
expose_user_details_fields: false
entity_title: entityTitle
entity_type: entityType
entity_bundle: entityBundle
entity_identifier: entityId
group_label: groupLabel
drupal_language: drupalLanguage
drupal_country: drupalCountry
site_name: siteName
key_replacements:
  - ''
_core:
  default_config_hash: N67AkcKPlikWJbwxABv6MSMpGuXe36qWZfH88pEzeqc
langcode: fi
