add_page_meta: true
output_terms: true
output_fields: false
group: false
lib_helper: false
entity_meta:
  - ''
enable_ia: false
ia_depth: 3
ia_category_primary: primaryCategory
ia_category_sub: subCategory
vocabs:
  - ''
expose_user_details: ''
expose_user_details_roles:
  - ''
current_user_meta:
  - ''
expose_user_details_fields: false
entity_title: entityTitle
entity_type: entityType
entity_bundle: entityBundle
entity_identifier: entityId
group_label: groupLabel
drupal_language: drupalLanguage
drupal_country: drupalCountry
site_name: siteName
key_replacements:
  - ''
_core:
  default_config_hash: N67AkcKPlikWJbwxABv6MSMpGuXe36qWZfH88pEzeqc
langcode: fi
