_core:
  default_config_hash: MymgTM4i959vZLJ3F-hpn_ntX-johso5eQqRm-03r0Y
langcode: fi
applies_admin_routes: true
include_invalid_paths: false
excluded_paths: ''
replaced_titles: ''
custom_paths: ''
include_home_segment: true
home_segment_title: Opetustilat
home_segment_keep: false
include_title_segment: false
title_from_page_when_available: true
title_segment_as_link: true
segments_separator: null
use_menu_title_as_fallback: false
use_page_title_as_menu_title_fallback: false
remove_repeated_segments: true
language_path_prefix_as_segment: false
absolute_paths: false
hide_single_home_item: false
term_hierarchy: false
add_structured_data_json_ld: false
capitalizator_ignored_words: {  }
capitalizator_forced_words: {  }
capitalizator_forced_words_case_sensitivity: false
capitalizator_forced_words_first_letter: false
follow_redirects: true
