include_home_segment: true
home_segment_title: Spaces
include_title_segment: false
language_path_prefix_as_segment: false
use_menu_title_as_fallback: false
remove_repeated_segments: true
_core:
  default_config_hash: MymgTM4i959vZLJ3F-hpn_ntX-johso5eQqRm-03r0Y
include_invalid_paths: false
excluded_paths: ''
segments_separator: null
title_segment_as_link: true
title_from_page_when_available: true
langcode: fi
