logo_text: 'Helsingin Yliopisto'
logo_path: 'https://www.helsinki.fi'
copyright_text: '(c) Helsingin Yliopisto'
contact_info: "<p>PL 3 (Fabianinkatu 33) \r\n00014 Helsingin yliopisto</p>\r\n\r\n<p>Puhelinvaihde: 02941 911</p>"
spaces_contact_info: "UNI­VERSITY OF HEL­SINKI\r\nP.O. Box 3 (Fabianinkatu 33) 00014 University of Helsinki\r\n\r\nSwitchboard: +358 (0) 2941 911"
