name: tilat
recipe: drupal10

config:
  webroot: web
  via: nginx
  php: '8.1'
  database: mariadb:10.3
  xdebug: false
  composer_version: 2-latest

tooling:
  build.sh:
    service: appserver
    description: Execute build.sh
    cmd:
      - ./build.sh
  drush:
    service: appserver
    cmd: drush --root=/app/web
  node:
    service: node
  npm:
    description: "Runs npm commands"
    service: node

services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver

  # Making SequelPro access easier with static port: https://docs.devwithlando.io/tutorials/external-access.html
  # Edit, not strictly necessary.
  database:
    portforward: 33306
    scanner: false

  appserver:
    build_as_root:
      - "apt-get update -y"
      - "apt-get install python3-yaml -y"
      - "apt-get install sudo nano vim mlocate -y"
      # Make sure our custom drush.yml is active either by copying or symlinking.
      # - "/bin/cp /app/web/sites/default/drush.yml /var/www/.drush/drush.yml"
      #- "ln -sf /app/web/sites/default/drush.yml ~/.drush/drush.yml"
      #- "ln -sf /app/drush/drushrc.php /var/www/.drush/drushrc.php"
      #- "ln -sf /app/drush/drush.yml /var/www/.drush/drush.yml"
    overrides:
      environment:
        WKV_SITE_ENV: lando
        DB_PASS_DRUPAL: drupal10
        DB_USER_DRUPAL: drupal10
        DB_HOST_DRUPAL: database
        DB_NAME_DRUPAL: drupal10
        DRUSH_OPTIONS_URI: https://tilat.lndo.site
  node:
    type: node
proxy:
  mailhog:
    - mail.lndo.site

events:
  # Clear caches after a database import
  post-db-import:
    - appserver: cd /app/web && drush cr -y
  # Update modules after lando start.
  post-start:
    - appserver: cd /app && composer install

# Lando version when config tested
version: v3.11.0
