name: tilat
recipe: drupal8

config:
  webroot: web
  via: nginx
  php: '7.1'
  database: mariadb:10.1
  #xdebug: true

tooling:
  build.sh:
    service: appserver
    description: Execute build.sh
    cmd:
      - ./build.sh
  drush:
    service: appserver
    cmd: drush --root=/app/web
  node:
    service: node
  npm-install:
    service: node
    description: Execute `npm install`
    cmd:
      - "cd /app/web/themes/custom/uh_space && npm install"
  npm-build:
    service: node
    description: Execute `npm run build`
    cmd:
      - "cd /app/web/themes/custom/uh_space && npm run build"
  npm-fix:
    service: node
    description: Execute `npm audit fix --force`
    cmd:
      - "cd /app/web/themes/custom/uh_space && npm audit fix --force"

services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver

  # Making SequelPro access easier with static port: https://docs.devwithlando.io/tutorials/external-access.html
  # Edit, not strictly necessary.
  database:
    portforward: 33306
    scanner: false

  appserver:
    extras:
      - "apt-get update -y"
      - "apt-get install python-yaml -y"
      - "apt-get install sudo nano vim mlocate -y"
      # Make sure our custom drush.yml is active either by copying or symlinking.
      # - "/bin/cp /app/web/sites/default/drush.yml /var/www/.drush/drush.yml"
      #- "ln -sf /app/web/sites/default/drush.yml ~/.drush/drush.yml"
      #- "ln -sf /app/drush/drushrc.php /var/www/.drush/drushrc.php"
      - "ln -sf /app/drush/drush.yml /var/www/.drush/drush.yml"
    overrides:
        environment:
          WKV_SITE_ENV: lando
          DB_PASS_DRUPAL: drupal8
          DB_USER_DRUPAL: drupal8
          DB_HOST_DRUPAL: database
          DB_NAME_DRUPAL: drupal8
  node:
    type: node:10
    extras:
      - "apt-get update -y"
      - "apt-get install curl php-cli php-mbstring git unzip -y"
      - "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"
    run:
      - "cd /app/web/themes/custom/uh_space && npm install"
      - "cd /app/web/themes/custom/uh_space && npm run build"
proxy:
  mailhog:
    - mail.lndo.site

events:
  # Clear caches after a database import
  post-db-import:
    - appserver: cd /app/web && drush cr -y
  # Update modules after lando start.
  post-start:
    - appserver: cd /app && composer install

# Tested with Lando version
version: v3.0.3
