name: tilat
recipe: drupal8

config:
  webroot: web
  via: nginx
  php: 7.2
  database: mariadb:10.1
  xdebug: false
  composer_version: 1.10.17

tooling:
  build.sh:
    service: appserver
    description: Execute build.sh
    cmd:
      - ./build.sh
  drush:
    service: appserver
    cmd: drush --root=/app/web
  node:
    service: node
  npm:
    service: node
  npm-install:
    service: node
    description: Execute `npm install`
    cmd: "cd /app/web/themes/custom/uh_space && npm install"
  npm-build:
    service: node
    description: Execute `npm run build`
    cmd: "cd /app/web/themes/custom/uh_space && npm run build"
  npm-fix:
    service: node
    description: Execute `npm audit fix --force`
    cmd: "cd /app/web/themes/custom/uh_space && npm audit fix --force"
  npm-sass-rebuild:
    service: node
    description: Execute `npm rebuild node-sass`
    cmd: "cd /app/web/themes/custom/uh_space && npm rebuild node-sass"
  update:
    description: Update local database.
    cmd:
      - appserver: /app/conf/lando/update.sh

services:
  appserver:
    build:
      - composer install
    build_as_root:
      - "apt-get update -y"
      - "apt-get install python-yaml -y"
      - "apt-get install sudo nano vim mlocate -y"
    overrides:
      environment:
        WKV_SITE_ENV: lando
        DB_PASS_DRUPAL: drupal8
        DB_USER_DRUPAL: drupal8
        DB_HOST_DRUPAL: database
        DB_NAME_DRUPAL: drupal8
  database:
    portforward: true
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  node:
    type: node
    build:
      - "cd /app/web/themes/custom/uh_space && npm install"
    build_as_root:
      - "apt-get update -y"
      - "apt-get install curl php-cli php-mbstring git unzip -y"
      - "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"

proxy:
  mailhog:
    - mail-tilat.lndo.site

# Tested with Lando version
version: v3.0.19
