settings:
  default_submit_button_label: Skicka
  default_reset_button_label: Återställ
  default_wizard_prev_button_label: '< Föregående sida'
  default_wizard_next_button_label: 'Nästa sida >'
  default_wizard_start_label: Från
  default_wizard_confirmation_label: Slutförd
  default_preview_next_button_label: Förhandsgranska
  default_preview_label: Förhandsgranska
  default_draft_button_label: 'Spara utkast'
  default_draft_saved_message: 'Formulär sparat. Du kan återvända till detta formulär senare och fortsätta inmatningen.'
element:
  default_more_title: Mer
  default_section_title_tag: h2
