<?php

use \Drupal\Core\Entity\EntityInterface;
use \Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 *  Implements hook_theme().
 */
function uh_space_site_theme($existing, $type, $theme, $path) {
  return [
    'hero_block' => [
      'variables' => [
        'background_image' => [],
        'title' => [],
        'lead' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_entity_extra_field_info().
 */
function uh_space_site_entity_extra_field_info() {
  $extra_field = [];

  $extra_field['node']['space']['display']['field_smart_equipment_information'] = [
    'label' => t('Smart Equipment Information'),
    'description' => t('Displays space equipment information and falls back to building equipment information.'),
    'weight' => 100,
    'visible' => TRUE,
  ];

  return $extra_field;
}

/**
 * Implements hook_ds_pre_render_alter().
 */
function uh_space_site_ds_pre_render_alter(&$layout_render_array, $context, &$vars) {
  if ($context['bundle'] == 'space' && $context['view_mode'] == 'full') {
    // Unset building equipment information if space equipment information is set.
    if (!empty($layout_render_array['left']['group_equipment']['field_equipment_information']['#items'])) {
      unset($layout_render_array['left']['group_equipment']['ds_chains:node/space/field_building/field_equipment_information']);
    }
  }
}

/**
 * Implements hook_views_query_alter().
 */
function uh_space_site_views_query_alter($view, $query) {
  // Change contextual filter to OR type so it's enough that either
  // parent term ID or current term ID matches the provided value.
  if ($view->id() == 'space_navigation' && $view->current_display == 'campus_buildings') {
    $query->where[0]['type'] = 'OR';
  }
}
